blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/DamienDemontis/GigFlux/security/advisories
    about: Please report security issues privately via advisories.